default:
  image: "gradle:8.14.3-jdk17"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_STRATEGY: clone
  GIT_DEPTH: 0
  ANDROID_COMPILE_SDK: "35"
  ANDROID_BUILD_TOOLS: "35.0.0"
  ANDROID_SDK_TOOLS: "9477386"

stages:
  - build
  - test

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk-linux "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk-linux "platform-tools" >/dev/null
  - echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk-linux "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew

build_zoratype_debug:
  stage: build
  script:
    - ./gradlew assembleUnstableDebug
  artifacts:
    name: "zoratype-debug-$CI_COMMIT_SHORT_SHA"
    paths:
      - build/outputs/apk/unstable/debug/*.apk
    expire_in: 1 week

build_zoratype_release:
  stage: build
  script:
    - ./gradlew assembleStableRelease
  artifacts:
    name: "zoratype-release-$CI_COMMIT_SHORT_SHA"
    paths:
      - build/outputs/apk/stable/release/*.apk
    expire_in: 1 month
  when: manual

test_zoratype:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml